// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// GaussianDensities
NumericVector GaussianDensities(double const_term, NumericMatrix obs_minus_cmean);
RcppExport SEXP _sstvars_GaussianDensities(SEXP const_termSEXP, SEXP obs_minus_cmeanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type const_term(const_termSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type obs_minus_cmean(obs_minus_cmeanSEXP);
    rcpp_result_gen = Rcpp::wrap(GaussianDensities(const_term, obs_minus_cmean));
    return rcpp_result_gen;
END_RCPP
}
// GaussianDensities2
arma::vec GaussianDensities2(arma::mat obs, arma::mat mean, arma::mat covmat);
RcppExport SEXP _sstvars_GaussianDensities2(SEXP obsSEXP, SEXP meanSEXP, SEXP covmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type covmat(covmatSEXP);
    rcpp_result_gen = Rcpp::wrap(GaussianDensities2(obs, mean, covmat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sstvars_GaussianDensities", (DL_FUNC) &_sstvars_GaussianDensities, 2},
    {"_sstvars_GaussianDensities2", (DL_FUNC) &_sstvars_GaussianDensities2, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sstvars(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
