#' @title Perform Portmanteau test for a STVAR model
#'
#' @description \code{Portmanteau_test} performs Portmanteau test for remaining autocorrealtion
#'   in the residuals  for a STVAR model
#'
#' @param stvar an object of class \code{'stvar'} generated by \code{fitSTVAR} or \code{STVAR}.
#' @details The implemented test is discussed, for instance, in Lütkepohl (2005), Section 4.4.3.
#' @return A list with class "hypotest" containing the test results and arguments used to calculate the test.
#' @seealso \code{\link{LR_test}}, \code{\link{Rao_test}}, \code{\link{fitSTVAR}}, \code{\link{STVAR}},
#'   \code{\link{diagnostic_plot}}, \code{\link{profile_logliks}},
#' @references
#'   \itemize{
#'    \item Lütkepohl H. 2005. New Introduction to Multiple Time Series Analysis,
#'            \emph{Springer}.
#'   }
#' @examples
#' # FILL IN
#' @export

Portmanteau_test <- function(stvar) {
  params <- stvar$params


  # Calculate the test statistic

  # Calculate the p-value
  df <- NULL
  p_value <- pchisq(test_stat, df=df, lower.tail=FALSE)

  # Return
  # structure(list(stvar=stvar,
  #                A=A,
  #                c=c,
  #                df=df,
  #                test_stat=test_stat,
  #                df=df,
  #                p_value=p_value,
  #                type="Wald test"),
  #           class="hypotest")
  NULL # Maybe hypotest class would actually work here?
}

