# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Gaussian_densities_Cpp
#' @title Calculate log multivariate Gaussian densities
#' @description Calculates logs of multivariate Gaussian densities with varying mean
#'   and varying covariance matrix AND EXCLUDING the constant term of the density
#'   (the constant is calculated and added in R code). The varying conditional covariance
#'   matrix is calculated within the function from the regime covariance matrices and
#'   transition weights.
#'
#' @param obs a \eqn{(T \times d)} matrix such that the i:th row contains the vector
#'  \eqn{y_{i}=(y_{1i},...,y_{di})} \eqn{(dx1)}. That is, the initial values are
#'  excluded but the last observations is included.
#' @param means a \eqn{(T \times d)} matrix such that the i:th row contains the
#'   conditional mean of the process \eqn{\mu_{y,i}}.
#' @param covmats a \eqn{(d \times d \times M)} array such that the slice \code{[, , m]}
#'   contains the conditional covariance matrix of regime m.
#' @param alpha_mt a \eqn{(T \times M)} matrix such that \code{[t, m]} contains the time t
#'   transition weights of the m:th regime.
#' @return a numeric vector containing the multivariate Gaussian densities, excluding the constant term.
#' @keywords internal
Gaussian_densities_Cpp <- function(obs, means, covmats, alpha_mt) {
    .Call('_sstvars_Gaussian_densities_Cpp', PACKAGE = 'sstvars', obs, means, covmats, alpha_mt)
}

#' @name Gaussian_densities_const_Cpp
#' @title Calculate log multivariate Gaussian densities
#' @description Calculates logs of multivariate Gaussian densities with constant mean
#'   and constant covariance matrix AND EXCLUDING the constant term of the density
#'   (the constant is calculated and added in R code).
#'
#' @param obs a \eqn{(T \times dp)} matrix such that the i:th row contains the vector
#'  \eqn{(y_{i-1}',...,y_{i-p}')} \eqn{((dp)x1)}, where \eqn{y_{i}=(y_{1i},...,y_{di})}
#'  \eqn{(dx1)}. That is, the initial values are included but the last observations not.
#' @param mean the \eqn{((dp)x1)} mean vector, \code{rep(all_mu[,m], times=p)}, that is the same for
#'  all observations.
#' @param cholcovmat the \eqn{(dp \times dp)} covariance matrix that is the same for all observations.
#' @details This function is used in the relative density transition weights with Gaussian regimes.
#' @return a numeric vector containing the multivariate Gaussian densities, excluding the constant term.
#' @keywords internal
Gaussian_densities_const_Cpp <- function(obs, mean, cholcovmat) {
    .Call('_sstvars_Gaussian_densities_const_Cpp', PACKAGE = 'sstvars', obs, mean, cholcovmat)
}

#' @name get_mu_yt_Cpp
#' @title Calculate the conditional means of the process
#' @description Calculates the conditional means \eqn{\mu_{y,t}} of the process
#'
#' @param obs a \eqn{(T \times dp)} matrix such that the i:th row contains the vector
#'   \eqn{(y_{i-1},...,y_{i-p})} \eqn{((dp)x1)}, where \eqn{y_{i}=(y_{1i},...,y_{di})}
#'   \eqn{(dx1)}. That is, the initial values are included but the last observations not.
#' @param all_phi0 a \eqn{(d \times M)} matrix such that the m:th column contains the
#'   intercept parameters of the m:th regime.
#' @param all_A a \eqn{(d \times dp \times M)} array such that the slice \code{[, , m]}
#'   contains the AR matrices of the m:th regime cbinded together: \eqn{[A_{m,1}:...:A_{m,p}]}.
#' @param alpha_mt a \eqn{(T \times M)} matrix such that \code{[t, m]} contains the time t
#'   transition weights of the m:th regime.
#' @return a \eqn{(T \times d)} matrix such that the i:th row contains the conditional
#'   mean of the process.
#' @keywords internal
get_mu_yt_Cpp <- function(obs, all_phi0, all_A, alpha_mt) {
    .Call('_sstvars_get_mu_yt_Cpp', PACKAGE = 'sstvars', obs, all_phi0, all_A, alpha_mt)
}

#' @name get_multisets_Cpp
#' @title Generate all d-element multisets
#' @description Generates all d-element multisets in \eqn{\lbrace 1,...,n \rbrace}
#'   ordered in a lexicographic order.
#'
#' @param n positive integer specifying the value n in \eqn{\lbrace 1,...,n \rbrace}.
#' @param d positive integer specifying the size of the multisets.
#' @param N the binomial coefficient \code{choose(n + d - 1, d)} (calculated in R wrapper)
#' @details This function is used in approximation of the joint spectral radius.
#' @return a numeric matrix with N rows and d columns, containing each multiset in each row, ordered
#'   lexicographically from top to bottom.
#' @keywords internal
get_multisets_Cpp <- function(n, d, N) {
    .Call('_sstvars_get_multisets_Cpp', PACKAGE = 'sstvars', n, d, N)
}

#' @name dec2binar
#' @title Transform a decimal to a binary array
#' @description Transforms a decimal to a binary array with an additional
#'   element saving the number of ones in the array. Helper function for
#'   \code{get_permanent_Cpp}.
#'
#' @param n the index determining the submatrix of the square matrix A the permanent is calculated for.
#' @param dim the number of rows (or columns) in the square matrix A the permanent is calculated for.
#' @details Helper function for \code{get_permanent_Cpp}, which calculates the
#'   permanent of a square matrix using the Ryser's formula.
#'   This function is an Rcpp implementation of the C++ code written by "hanzzoid"
#'   on the "Code Project" website
#'   \url{https://www.codeproject.com/Articles/21282/Compute-Permanent-of-a-Matrix-with-Ryser-s-Algorit}.
#'   Modified code reproduced under The Code Project Open licence
#'   (\url{https://www.codeproject.com/info/cpol10.aspx}).
#' @return Returns a characteric string that allows to select the submatrix.
#' @keywords internal
NULL

#' @name get_permanent_Cpp
#' @title Calculate the permanent of a matrix
#' @description Calculates the permanent of a square matrix using the Ryser's formula.
#'
#' @param A a square matrix
#' @details Calculates the permanent of a square matrix using Ryser's formula.
#'   This function is an Rcpp implementation of the C++ code written by "hanzzoid"
#'   on the "Code Project" website
#'   \url{https://www.codeproject.com/Articles/21282/Compute-Permanent-of-a-Matrix-with-Ryser-s-Algorit}.
#'   Modified code reproduced under The Code Project Open licence
#'   (\url{https://www.codeproject.com/info/cpol10.aspx}).
#' @return Returns the permanent of the matrix A (a real number)
#' @keywords internal
get_permanent_Cpp <- function(A) {
    .Call('_sstvars_get_permanent_Cpp', PACKAGE = 'sstvars', A)
}

