# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Gaussian_densities_Cpp
#' @title Calculate log multivariate Gaussian densities
#' @description Calculates logs of multivariate Gaussian densities with constant mean
#'   and constant covariance matrix AND EXCLUDING the constant term of density
#'   (the constant is calculated and added in R code).
#'
#' @param obs a \eqn{(T \times dp)} such that the i:th row of the matrix contains
#'  the vector \eqn{(y_{i-1}',...,y_{i-p}') }\code{rep(all_mu[,m], times=p)}
#'  \eqn{((dp)x1)}, where \eqn{y_{i}=(y_{1i},...,y_{di})} \eqn{(dx1)}. That is, the initial values are
#'  included but the last observations not (used in relative dens transition weights).
#' @param mean the \eqn{((dp)x1)} mean vector, \code{rep(all_mu[,m], times=p)}, that is the same for
#'  all observations.
#' @param covmat the \eqn{(dp \times dp)} covariance matrix that is the same for all
#'   observations.
#' @return a numeric vector containing the multivariate Gaussian densities, excluding the constant term.
#' @keywords internal
Gaussian_densities_Cpp <- function(obs, mean, covmat) {
    .Call('_sstvars_Gaussian_densities_Cpp', PACKAGE = 'sstvars', obs, mean, covmat)
}

#' @name Gaussian_densities_const_Cpp
#' @title Calculate log multivariate Gaussian densities
#' @description Calculates logs of multivariate Gaussian densities with constant mean
#'   and constant covariance matrix AND EXCLUDING the constant term of density
#'   (the constant is calculated and added in R code).
#'
#' @param obs a \eqn{(T \times dp)} such that the i:th row of the matrix contains
#'  the vector \eqn{(y_{i-1}',...,y_{i-p}') }\code{rep(all_mu[,m], times=p)}
#'  \eqn{((dp)x1)}, where \eqn{y_{i}=(y_{1i},...,y_{di})} \eqn{(dx1)}. That is, the initial values are
#'  included but the last observations not (used in relative dens transition weights).
#' @param mean the \eqn{((dp)x1)} mean vector, \code{rep(all_mu[,m], times=p)}, that is the same for
#'  all observations.
#' @param covmat the \eqn{(dp \times dp)} covariance matrix that is the same for all
#'   observations.
#' @return a numeric vector containing the multivariate Gaussian densities, excluding the constant term.
#' @keywords internal
Gaussian_densities_const_Cpp <- function(obs, mean, covmat) {
    .Call('_sstvars_Gaussian_densities_const_Cpp', PACKAGE = 'sstvars', obs, mean, covmat)
}

